### ISSUE TITLE
Redirect Register Page should appear after Non-Account Owner attempts purchase

### ISSUE THREAD

**Issue by JTY009** [RytisJ/qa_play_project#125]
If a customer who does not / created an account then they cannot purchase an item. 

At the moment the first image is them going to select "Continue to Payment"
![checkout 1](https://cloud.githubusercontent.com/assets/20016950/16988531/9d0b500c-4e88-11e6-973f-c84ff636766e.png)

Then this error message appears
![checkout 2](https://cloud.githubusercontent.com/assets/20016950/16988535/a12dbee0-4e88-11e6-8aef-552d31952d47.png)

I believe the register page redirect should be here

**Comment by Smudgey** [comment]
cc @thelemens

**Comment by Smudgey** [comment]
When using session, you can do a check to see if the user if logged in, rather than going straight to accessing the data.

As an example `request.session.get("connected").isEmpty` will return true if the user is not currently logged in, false if they are logged in. This way you can redirect them to register.

**Comment by Smudgey** [comment]
Found an issue with viewing the basket, raised as a separate issue in #126

**Comment by JTY009** [comment]
Need to check again and then merge

**Comment by JTY009** [comment]
done
