### ISSUE TITLE
Currently, the - and + symbols in the basket do not work as intended

### ISSUE THREAD

**Issue by RytisJ** [RytisJ/qa_play_project#141]

**Comment by Smudgey** [comment]
The + and - symbols change the value by 2 instead of 1. There is another bug, in the case of only 1 stock of a product, the + button can be pressed and stays pressed not seemingly doing anything. Same for - when reaching zero.

![image](https://cloud.githubusercontent.com/assets/7337624/17030238/90390f98-4f66-11e6-8b95-c9242ba2342e.png)

![image](https://cloud.githubusercontent.com/assets/7337624/17030249/9a4add04-4f66-11e6-9b37-2b134dced667.png)

**Comment by thelemens** [comment]
The script had been imported twice, this has been removed.  Ref pull request #153
